# Generated by Django 5.1.1 on 2024-09-19 11:26

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=320)),
                ('gender', models.CharField(max_length=11)),
                ('date_of_birth', models.DateField(default=datetime.date(1000, 1, 1), max_length=10)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
